import { ArrowRight, BarChart3, CheckCircle2, ChevronRight, Globe2, LockKeyhole, Network, Play, ScanSearch, Shield, Sparkles, Timer, Workflow } from "lucide-react";

const stats = [["12.4M+", "transactions indexed"], ["38s", "median attribution"], ["96.8%", "cluster confidence"], ["24/7", "surveillance coverage"]];

export function LandingPage({ onNavigate }) {
  return (
    <div className="landing-page">
      <header className="landing-nav">
        <button type="button" className="brand-lockup" onClick={() => window.scrollTo({ top: 0, behavior: "smooth" })}><span className="brand-mark"><Shield size={18} /></span><span><b>CHAKRAVYUH</b><small>I4C · NATIONAL ATTRIBUTION</small></span></button>
        <nav className="landing-links"><button type="button" onClick={() => onNavigate("about")}>About</button><button type="button" onClick={() => onNavigate("services")}>Services</button><button type="button" onClick={() => onNavigate("industries")}>Industries</button><button type="button" onClick={() => onNavigate("insights")}>Insights</button><button type="button" onClick={() => onNavigate("careers")}>Careers</button></nav>
        <div className="landing-actions"><button type="button" className="text-btn" onClick={() => onNavigate("login")}>Sign in</button><button type="button" className="primary-btn" onClick={() => onNavigate("signup")}>Request access <ArrowRight size={14} /></button></div>
      </header>

      <main>
        <section className="landing-hero">
          <div className="hero-orbit orbit-one parallax-layer" /><div className="hero-orbit orbit-two parallax-layer" />
          <div className="hero-content reveal-up"><div className="eyebrow"><span className="live-pulse" /> National cyber crime reporting portal integrated</div><h1>Move from wallet<br /><em>to evidence.</em></h1><p>Real-time blockchain intelligence for investigators. Trace suspect wallets, attribute receiving VASPs, and turn fragmented transactions into an actionable case narrative.</p><div className="hero-actions"><button type="button" className="primary-btn primary-btn-large" onClick={() => onNavigate("signup")}>Start an investigation <ArrowRight size={17} /></button><button type="button" className="secondary-btn" onClick={() => onNavigate("services")}><Play size={15} /> Explore the platform</button></div><div className="hero-trust"><span><CheckCircle2 size={14} /> Section 91 ready</span><span><CheckCircle2 size={14} /> Multi-chain native</span><span><CheckCircle2 size={14} /> Evidence-first</span></div></div>
          <div className="hero-console glass-panel reveal-scale parallax-layer"><div className="console-bar"><span><span className="live-pulse" /> LIVE ATTRIBUTION ENGINE</span><span className="mono">CASE #I4C-9921</span></div><div className="console-map"><div className="map-grid" /><div className="map-line line-a" /><div className="map-line line-b" /><div className="map-node node-a"><ScanSearch size={14} /><span>Reported wallet</span></div><div className="map-node node-b"><Network size={14} /><span>Layering wallet</span></div><div className="map-node node-c"><Globe2 size={14} /><span>VASP endpoint</span></div><div className="console-tooltip"><span className="eyebrow">Attribution confidence</span><strong>96.8%</strong><small>Direct deposit cluster matched</small></div></div><div className="console-footer"><span><Timer size={14} /> 00:00:38 latency</span><span className="text-emerald-300">● Node synced</span></div></div>
        </section>

        <section className="stat-strip">{stats.map(([value, label]) => <div key={label}><strong>{value}</strong><span>{label}</span></div>)}</section>

        <section id="platform" className="landing-section"><div className="section-intro"><div className="eyebrow"><Sparkles size={13} /> One system. Every signal.</div><h2>From raw transactions<br /><span>to clear decisions.</span></h2><p>Chakravyuh connects the investigative workflow in one secure workspace built for speed, chain complexity, and courtroom-grade evidence.</p></div><div className="feature-grid"><Feature icon={ScanSearch} title="Trace in real time" text="Ingest any victim-reported address and map multi-hop fund movement across supported chains." /><Feature icon={BarChart3} title="Attribute with confidence" text="Cluster exchange wallets, identify the nearest VASP, and surface laundering typologies." /><Feature icon={LockKeyhole} title="Preserve the record" text="Create standardized notices and export an auditable chain of custody for every case." /></div></section>

        <section id="workflow" className="landing-section workflow-section"><div className="section-intro"><div className="eyebrow"><Workflow size={13} /> Built for the investigation room</div><h2>A faster path from<br /><span>report to recovery.</span></h2></div><div className="workflow-grid">{["Ingest", "Traverse", "Attribute", "Act"].map((step, index) => <div className="workflow-step" key={step}><span>0{index + 1}</span><div><h3>{step}</h3><p>{["Connect NCRP and victim reports.", "Follow flows across hops and bridges.", "Match clusters to exchange endpoints.", "Issue freeze directives with evidence."][index]}</p></div>{index < 3 && <ChevronRight className="workflow-arrow" size={18} />}</div>)}</div></section>

        <section className="landing-section signal-section"><div className="section-intro"><div className="eyebrow"><Globe2 size={13} /> Built for complex crime patterns</div><h2>Every chain tells<br /><span>a different story.</span></h2><p>One investigation surface for task fraud, investment scams, ransomware, phishing, darknet flows, and organized laundering networks.</p></div><div className="signal-grid">{["Cross-chain bridges", "Mixers and tumblers", "Burner wallets", "Exchange clusters", "DeFi protocols", "Risk typologies"].map((signal, index) => <div className="signal-card glass-panel" key={signal}><span>0{index + 1}</span><strong>{signal}</strong><ChevronRight size={15} /></div>)}</div></section>

        <section className="landing-section intelligence-section"><div className="section-intro"><div className="eyebrow"><BarChart3 size={13} /> Intelligence brief</div><h2>Stay ahead of<br /><span>the next move.</span></h2></div><div className="insight-list">{[["FIELD NOTE", "How peel-chain behavior exposes the final VASP endpoint", "04 min read"], ["OPERATIONS", "Building a defensible digital evidence trail from day one", "06 min read"], ["NETWORKS", "What cross-chain laundering patterns look like in 2026", "08 min read"]].map(([tag, title, time]) => <article className="insight-row" key={title}><span className="eyebrow">{tag}</span><h3>{title}</h3><span>{time}</span><ArrowRight size={16} /></article>)}</div></section>

        <section id="security" className="landing-section security-section"><div className="security-card glass-panel"><div><div className="eyebrow"><Shield size={13} /> Designed for public trust</div><h2>Intelligence that stands<br /><span>up in court.</span></h2><p>Every finding is anchored to verifiable transaction hashes, timestamps, and explainable attribution signals. No black boxes between an alert and an action.</p><button type="button" className="secondary-btn" onClick={() => onNavigate("signup")}>Request agency access <ArrowRight size={15} /></button></div><div className="security-art"><div className="security-ring"><LockKeyhole size={27} /></div><div className="security-chip chip-one">65B Evidence ready</div><div className="security-chip chip-two">Encrypted session</div></div></div></section>
      </main>
      <footer className="landing-footer"><span>CHAKRAVYUH · I4C NATIONAL ATTRIBUTION</span><span>Ministry of Home Affairs · CIS Division</span></footer>
    </div>
  );
}

function Feature({ icon: Icon, title, text }) { return <article className="feature-card glass-panel"><div className="feature-icon"><Icon size={18} /></div><h3>{title}</h3><p>{text}</p><ArrowRight className="feature-arrow" size={16} /></article>; }
